version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: saturday
      time: "10:00"
      timezone: "Asia/Tokyo"
    reviewers:
      - unasuke
  - package-ecosystem: "cargo"
    directory: "src-tauri"
    schedule:
      interval: "weekly"
      day: saturday
      time: "10:00"
      timezone: "Asia/Tokyo"
    reviewers:
      - unasuke
